# pytest-bdd-allure-project/pytest.ini

[pytest]
# Tell pytest where to find BDD feature files
bdd_features_base_dir = features/

# Tell pytest where to find step definition modules (optional, pytest can discover them)
# python_files = step_definitions/*.py tests/*.py

# Add markers if needed, e.g., for specific test types
markers =
    ui: marks UI tests
    api: marks API tests
    TM: Test Management ID

# Allure report directory (where JSON results will be stored)
allure_report_dir = allure-results
# To automatically clean the allure-results directory before each run:
# addopts = --alluredir=allure-results --clean-alluredir
addopts = --alluredir=allure-results --junitxml=test-results/results.xml
